#!/bin/bash
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'
echo -e "${GREEN}Enter link:"
read link
echo -e "${BLUE}Downloading..."
youtube-dl -o '/mnt/[ВСТАВЬТЕ СЮДА РАСПОЛОЖЕНИЕ]/%(title)s.%(ext)s' --embed-thumbnail -x --audio-format mp3 --audio-quality 0 $link
echo -e "${NC}"


